name: Unit Test Workflow
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
permissions:
  contents: read
  packages: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Java
        uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2 # v1.4.3
        with:
          java-version: 11
      - name: Install SBT
        uses: ./.github/workflows/actions/install-sbt
      - name: Install dxpy and other dependencies
        uses: ./.github/workflows/actions/install-dxpy
      - name: Common Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project common' scalafmtCheckAll
          sbt 'project common' test
          sbt 'project common' publishLocal
      - name: API Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH_TOKEN: ${{ secrets.DX_STAGING_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.local/bin"

          # set up DNAnexus staging environment
          dx login --noprojects --staging --token $AUTH_TOKEN
          PROJECT=dxCompiler_playground
          dx select $PROJECT

          sbt 'project api' scalafmtCheckAll
          sbt 'project api' test
          sbt 'project api' publishLocal
      - name: Protocols Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project protocols' scalafmtCheckAll
          sbt 'project protocols' test
      - name: Yaml Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project yaml' scalafmtCheckAll
          sbt 'project yaml' test
