name : Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Common Unit Tests
        run: |
          sbt 'project common' test
          sbt 'project common' publishLocal
      - name: API Unit Tests
        run: |
          sbt 'project api' test
          sbt 'project api' publishLocal
      - name: Protocols Unit Tests
        run: |
          sbt 'project protocols' test
      - name: Scala formatting
        run: |
          sbt scalafmtCheckAll
