name: Unit Test Workflow
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Check Scala formatting
        run: |
          sbt scalafmtCheckAll
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install dxpy and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https wget git openssh-server tree python3 python3-pip python3-venv
          pip3 install setuptools wheel
          pip3 install termcolor
          pip3 install dxpy
      - name: Common Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project common' test
          sbt 'project common' publishLocal
      - name: API Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH_TOKEN: ${{ secrets.DX_STAGING_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.local/bin"

          # set up DNAnexus staging environment
          dx login --noprojects --staging --token $AUTH_TOKEN
          PROJECT=dxCompiler_playground
          dx select $PROJECT

          sbt 'project api' test
          sbt 'project api' publishLocal
      - name: Protocols Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project protocols' test
      - name: Yaml Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project yaml' test
