# TODO: update conda-forge recipe
name: dxFileAccessProtocols Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'dxFileAccessProtocols version'
        required: true

jobs:
  run-release:
    name: dxFileAccessProtocols Release
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Version check
        run: |
          protocols_snapshot=`grep -c "SNAPSHOT" ./protocols/src/main/resources/application.conf`
          if [ "$protocols_snapshot" -ne "0" ]; then
            echo "dxFileAccessProtocols version contains '-SNAPSHOT'; releases cannot have snapshot versions"
            exit 1
          fi
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # make sure we have latest dependency versions
          sbt 'project common' publishLocal
          sbt 'project api' publishLocal
      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project protocols' test
      - name: Assembly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project protocols' assembly
          mv ./protocols/target/dxFileAccessProtocols.jar ./dxFileAccessProtocols-${{ github.event.inputs.release-version }}.jar
      - name: Scala formatting
        run: |
          sbt 'project protocols' scalafmtCheckAll
      - name: Extract release notes and set version in application.conf files
        id: update-release
        run: |
          # Update the config file with the newest version
          sed -i 's/version.*$/version = "${{ github.event.inputs.release-version }}"/' ./protocols/src/main/resources/application.conf

          # Extract release notes for the release into a temporary (unpushed) file
          # It is expected the RELEASE_NOTES.md has already an entry for the version being
          # released. The section should start with '## <version>', e.g. ## 1.0.0 2021-01-01
          # The file will be read by the create-release step
          RELEASE_NOTES_PATH="./protocols/release_notes_${{ github.event.inputs.release-version }}.md"
          sed -n '/## ${{ github.event.inputs.release-version }}/,/##/p' api/RELEASE_NOTES.md | sed '1d; $d' > $RELEASE_NOTES_PATH
          echo ::set-output name=release-notes-path::$(echo "${RELEASE_NOTES_PATH}")
      - name: Commit changes to application.conf files
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Release ${{ github.event.inputs.release-version }}'
          add: '[
              "./protocols/src/main/resources/application.conf"
          ]'
          push: false
          tag: ${{ github.event.inputs.release-version }}
      - name: Create release entry
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release-version }}
          release_name: dxFileAccessProtocols ${{ github.event.inputs.release-version }}
          body_path: ${{ steps.update-release.outputs.release-notes-path }}
          draft: true
          prerelease: false
      - name: Upload assembly JAR
        id: upload-release-assembly
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the "Create release entry" step above, referencing it's ID to get its outputs object,
          # which include a `upload_url`. See this blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./dxFileAccessProtocols-${{ github.event.inputs.release-version }}.jar
          asset_name: dxFileAccessProtocols-${{ github.event.inputs.release-version }}.jar
          asset_content_type: application/jar
      - name: Push local release branch and tag to origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull
          git push origin HEAD:${{ github.ref }}
          git push origin HEAD:${{ github.event.inputs.release-version }}
      - name: Rollback release if unsuccessfull
        if: ${{ cancelled() || failure() }}
        uses: author/action-rollback@stable
        with:
          release_id: ${{ steps.create-release.outputs.id }}
          tag: ${{ github.event.inputs.release-version }}
          delete_orphan_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
