name: Publish Snapshot Workflow
on:
  push:
    branches:
      - develop

jobs:
  publish:
    name: Publish Snapshot
    runs-on: ubuntu-18.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check versions
        id: versions
        run: |
          common_version=`grep -o -P "\d+\.\d+\.\d+-SNAPSHOT" common/src/main/resources/application.conf`
          if [ -z "$common_version" ]; then
            echo "dxCommon version does not end in '-SNAPSHOT'; only snapshot versions are allowed in the develop branch"
            exit 1
          fi
          api_version=`grep -o -P "\d+\.\d+\.\d+-SNAPSHOT" ./api/src/main/resources/application.conf`
          if [ -z "$api_version" ]; then
            echo "dxApi version does not end in '-SNAPSHOT'; only snapshot versions are allowed in the develop branch"
            exit 1
          fi
          protocols_version=`grep -o -P "\d+\.\d+\.\d+-SNAPSHOT" ./protocols/src/main/resources/application.conf`
          if [ -z "$protocols_version" ]; then
            echo "dxFileAccessProtocols version does not end in '-SNAPSHOT'; only snapshot versions are allowed in the develop branch"
            exit 1
          fi
          echo ::set-output name=common_version::"${common_version}"
          echo ::set-output name=api_version::"${api_version}"
          echo ::set-output name=protocols_version::"${protocols_version}"
      - name: Delete existing common snapshot
        uses: actions/delete-package-versions@v1
        with:
          repo: dnanexus
          package-name: com.dnanexus.dxcommon
          package-version-ids: ${{ steps.versions.outputs.common_version }}
      - name: Delete existing api snapshot
        uses: actions/delete-package-versions@v1
        with:
          repo: dnanexus
          package-name: com.dnanexus.dxapi
          package-version-ids: ${{ steps.versions.outputs.api_version }}
      - name: Delete existing protocols snapshot
        uses: actions/delete-package-versions@v1
        with:
          repo: com.dnanexus.dnanexus
          package-name: dxfileaccessprotocols
          package-version-ids: ${{ steps.versions.outputs.protocols_version }}
      - name: Publish Snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project common' publish
          sbt 'project api' publish
          sbt 'project protocols' publish