name: Publish Snapshot Workflow
on:
  push:
    branches:
      - develop

jobs:
  publish:
    name: Publish Snapshot
    runs-on: ubuntu-18.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install other dependencies
        run: |
          sudo apt update -y && sudo apt install -y jq
      - name: Get snapshot versions
        id: versions
        run: |
          common_version=`grep -o -P "\d+\.\d+\.\d+-SNAPSHOT" common/src/main/resources/application.conf`
          if [ -z "$common_version" ]; then
            echo "dxCommon version does not end in '-SNAPSHOT'; only snapshot versions are allowed in the develop branch"
            exit 1
          fi
          common_query="{\"query\": \"query { repository(owner:\\\"dnanexus\\\", name:\\\"dxScala\\\") { packages(names:[\\\"com.dnanexus.dxcommon\\\"], first:1) { nodes { version(version:\\\"${common_version}\\\") { id } } } } }\" }"
          common_version_json=`curl \
            -X POST \
            -H "Accept: application/vnd.github.package-deletes-preview+json" \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d "$common_query" \
            https://api.github.com/graphql`
          common_version_id=`echo $common_version_json | jq .data.repository.packages.nodes[0].version.id`

          api_version=`grep -o -P "\d+\.\d+\.\d+-SNAPSHOT" ./api/src/main/resources/application.conf`
          if [ -z "$api_version" ]; then
            echo "dxApi version does not end in '-SNAPSHOT'; only snapshot versions are allowed in the develop branch"
            exit 1
          fi
          api_query="{\"query\": \"query { repository(owner:\\\"dnanexus\\\", name:\\\"dxScala\\\") { packages(names:[\\\"com.dnanexus.dxapi\\\"], first:1) { nodes { version(version:\\\"${api_version}\\\") { id } } } } }\" }"
          api_version_json=`curl \
            -X POST \
            -H "Accept: application/vnd.github.package-deletes-preview+json" \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d "$api_query" \
            https://api.github.com/graphql`
          api_version_id=`echo $api_version_json | jq .data.repository.packages.nodes[0].version.id`

          protocols_version=`grep -o -P "\d+\.\d+\.\d+-SNAPSHOT" ./protocols/src/main/resources/application.conf`
          if [ -z "$protocols_version" ]; then
            echo "dxFileAccessProtocols version does not end in '-SNAPSHOT'; only snapshot versions are allowed in the develop branch"
            exit 1
          fi
          protocols_query="{\"query\": \"query { repository(owner:\\\"dnanexus\\\", name:\\\"dxScala\\\") { packages(names:[\\\"com.dnanexus.dxfileaccessprotocols\\\"], first:1) { nodes { version(version:\\\"${protocols_version}\\\") { id } } } } }\" }"
          protocols_version_json=`curl \
            -X POST \
            -H "Accept: application/vnd.github.package-deletes-preview+json" \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d "$protocols_query" \
            https://api.github.com/graphql`
          protocols_version_id=`echo $protocols_version_json | jq .data.repository.packages.nodes[0].version.id`

          echo ::set-output name=common_version_id::"${common_version_id}"
          echo ::set-output name=api_version_id::"${api_version_id}"
          echo ::set-output name=protocols_version_id::"${protocols_version_id}"
      - name: Delete existing common snapshot
        uses: actions/delete-package-versions@v1
        if: ${{ steps.versions.outputs.common_version_id != '' }}
        with:
          repo: dnanexus
          package-name: com.dnanexus.dxcommon
          package-version-ids: ${{ steps.versions.outputs.common_version_id }}
      - name: Delete existing api snapshot
        uses: actions/delete-package-versions@v1
        if: ${{ steps.versions.outputs.api_version_id != '' }}
        with:
          repo: dnanexus
          package-name: com.dnanexus.dxapi
          package-version-ids: ${{ steps.versions.outputs.api_version_id }}
      - name: Delete existing protocols snapshot
        uses: actions/delete-package-versions@v1
        if: ${{ steps.versions.outputs.protocols_version_id != '' }}
        with:
          repo: com.dnanexus.dnanexus
          package-name: dxfileaccessprotocols
          package-version-ids: ${{ steps.versions.outputs.protocols_version_id }}
      - name: Publish Snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt 'project common' publish
          sbt 'project api' publish
          sbt 'project protocols' publish